language: php
os: linux
dist: xenial
php:
  - 7.4.11

before_script: composer install

script:
  - vendor/bin/phpunit tests
  - vendor/bin/phpstan analyse tests src
  - vendor/bin/psalm

after_success:
  - bash <(curl -s https://codecov.io/bash)
